version: 40
properties:
- name: deps_core_version
  value: v0.1.2-rc.6
  archived: false

jobs:
- name: Git Mirror Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger
    projects: VNLib.Plugins.Extensions
  - !BranchUpdateTrigger
    projects: VNLib.Plugins.Extensions
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        git clone @server_url@/vnuge/vnlib/VNLib.Core core --branch @property:deps_core_version@
    envVars:
    - name: GIT_SERVER_URL
      value: '@server_url@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        git clone @server_url@/vnuge/vnlib/VNLib.Core core --branch @property:deps_core_version@
    envVars:
    - name: GIT_SERVER_URL
      value: '@server_url@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: run vnbuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet gitversion core /updateprojectfiles
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        git clone @server_url@/vnuge/vnlib/VNLib.Core core --branch @property:deps_core_version@
    envVars:
    - name: GIT_SERVER_URL
      value: '@server_url@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Create git tag
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml tag-current-commit
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
          dotnet gitversion core /updateprojectfiles
          vnbuild build --no-delay --include @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
