version: 43
properties:
- name: deps_core_version
  value: master/v0.1.5
  archived: false
jobs:
- name: Git Mirror Push
  steps:
  - type: PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALWAYS
    optional: false
  triggers:
  - type: TagCreateTrigger
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - type: UseTemplateStep
    name: init deps
    templateName: init deps
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: run unit tests
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild test --include @project_name@ --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: '** -master'
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - type: UseTemplateStep
    name: init deps
    templateName: init deps
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: mock build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: mock publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: develop
    userMatch: anyone
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - type: UseTemplateStep
    name: init deps
    templateName: init deps
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Create git tag
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml tag-current-commit
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild build --no-delay --include @project_name@
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    branches: master
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

stepTemplates:
- name: init deps
  steps:
  - type: CommandStep
    name: init local deps
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        git clone @server_url@/@project_path@ --branch @branch@ @project_name@
        task -t @project_name@/Module.Taskfile.yaml configure-dep "DEP_REPO=@server_url@/vnuge/vnlib/VNLib.Core" "DEP_REVISION=@property:deps_core_version@" "DEP_DIR=core"
    useTTY: true
    condition: SUCCESSFUL
    optional: false