version: 37
jobs:
- name: GitHub Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: VNLib.Plugins.Extensions
  - !BranchUpdateTrigger
    projects: VNLib.Plugins.Extensions
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run vnbuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet-gitversion.exe core /updateprojectfiles
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Clone Dependencies
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/@project_name@ --branch @branch@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet-gitversion.exe core /updateprojectfiles
        vnbuild build --no-delay --include @project_name@ 
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
