version: 36
jobs:
- name: GitHub Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/VNLib.Plugins.Extensions.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: VNLib.Plugins.Extensions
  - !BranchUpdateTrigger
    projects: VNLib.Plugins.Extensions
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  steps:
  - !CommandStep
    name: Clone VNLib.Core into core
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/VNLib.Core core --branch master
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    checkoutPath: '@project_name@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml test
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
